#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-service-install

- name: Install required system packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get system architecture
  command: dpkg --print-architecture
  register: deb_architecture
  changed_when: False

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Create service directory
  file:
    path: "/opt/{{ service_name }}"
    state: directory
    mode: '0755'

- name: Place Systemd Unit file
  template:
    src: "service.unit.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: '0644'
  notify: Reload systemd

- name: Enable service (Prepare for first deployment)
  systemd:
    name: "{{ service_name }}"
    enabled: yes