---
# Configuration for Python Agent
service_name: "aq-agent"
project_type: "python-agent"
service_description: "Aquarius Python Agent"
# Versions (Updated by CI/CD)
agent_version: "agent-4b0c26b"
agent_image: "ghcr.io/israelsz/ansible-test"
